language: c++

compiler:
  - clang
  - gcc

before_install:
  #
  # install dependencies
  #
  - sudo apt-get install libboost-dev libboost-system-dev libboost-thread-dev

script:
  - cd build/linux
  - make
