language: c++

compiler:
  - clang
  - gcc

before_install:
  #
  # install dependencies
  #
  - sudo apt-get install libboost-dev libboost-system-dev libboost-thread-dev

script:
  - export LD_LIBRARY_PATH=`pwd`/bin
  - cd build/linux
  - make
  - make tests
  - ./bin/threadpool.bin
